name: CI pipeline for node and environment

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Select the node version"
        required: true
        default: latest
        type: choice
        options:
          - latest
          - 18
          - 19
          - 20

      environment:
        description: "Select the environment to deploy the project on"
        required: true
        default: 
        type: choice
        options:
          - mine 
          - production
          - dev
          - staging
jobs:
  build:
    # strategy:
    #   matrix:
    #     os:
    #       [ubuntu-latest,windows-latest]
    #     fail-fast: false 
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: running npm build and generating the output
        run: |
          cd chatApp/frontend
          ls 
          npm install
          npm run build

      - name: inspecting folder
        run: |
          cd chatApp/frontend
          ls 
      - name: Deploy to production
        if: ${{ inputs.environment == 'production' }}
        run: echo true condition

      - name: Print Work Space
        run: | 
          echo "The project is deployed in production environment"
          echo $GITHUB_WORKSPACE

      - name: Deploy to dev
        if: ${{ inputs.environment == 'dev' }}
        run: echo "The project is deployed in dev environment"

      - name: Deploy to staging
        if: ${{ inputs.environment == 'staging' }}
        run: |
          echo "Pushing image to Docker hub"
          docker build -t url-shortener-image:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag url-shortener-image:latest ${{ secrets.DOCKER_USERNAME }}/url-shortener-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener-image:latest

